In [1]:
# 東大のPython資料
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array((1,2,3))
print(b)

[1 2 3]


In [4]:
a

array([1, 2, 3])

In [6]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [7]:
type([1,2,3,4,5])

list

In [9]:
print(np.array([-1,0,1], dtype = np.int32))

[-1  0  1]


In [10]:
print(np.array([-1,0,1], dtype = np.float32))

[-1.  0.  1.]


In [11]:
print(np.array([-1,0,1], dtype = np.complex128))

[-1.+0.j  0.+0.j  1.+0.j]


In [12]:
print(np.array([-1,0,1], dtype = np.bool_))

[ True False  True]


In [14]:
print(np.array([[1,2],[3,4]]))

[[1 2]
 [3 4]]


In [15]:
print(np.array([[[1,2],[3,4]], [[5,6],[7,8]]]))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
print(np.array([[1,2],[3]]))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [17]:
a1 = np.array([0,1,2,3,4,5])

In [18]:
a2 = a1.reshape(2,3)

In [19]:
a2

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
a1[1] = 6
print(a1)

[0 6 2 3 4 5]


In [21]:
print(a2)

[[0 6 2]
 [3 4 5]]


In [22]:
a = np.array([0,1,2,3,4,5]).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [23]:
print(a.ravel())

[0 1 2 3 4 5]


In [25]:
elems = np.array([0,1,2,3,4,5])
a = elems.reshape(2,3).ravel()
elems[1] = 6
print(a)

[0 6 2 3 4 5]


In [35]:
a.dtype

dtype('int64')

In [28]:
a.shape

(6,)

In [29]:
a.ndim

1

In [30]:
a.size

6

In [31]:
a.flat

In [32]:
print(np.arange(3))

[0 1 2]


In [33]:
print(np.arange(0,1,.2))

[0.  0.2 0.4 0.6 0.8]


In [34]:
print(np.linspace(0,1,4))

[0.         0.33333333 0.66666667 1.        ]


In [36]:
print(np.zeros(4))

[0. 0. 0. 0.]


In [38]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
print(np.ones(4))

[1. 1. 1. 1.]


In [40]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [41]:
print(np.random.rand(4))

[0.97303821 0.63631897 0.48427249 0.16749364]


In [44]:
print(np.random.rand(2,3))

[[0.13440568 0.08150704 0.58525894]
 [0.90820252 0.92847203 0.84733871]]
