In [1]:
# 東大のPython資料
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array((1,2,3))
print(b)

[1 2 3]


In [4]:
a

array([1, 2, 3])

In [6]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [7]:
type([1,2,3,4,5])

list

In [9]:
print(np.array([-1,0,1], dtype = np.int32))

[-1  0  1]


In [10]:
print(np.array([-1,0,1], dtype = np.float32))

[-1.  0.  1.]


In [11]:
print(np.array([-1,0,1], dtype = np.complex128))

[-1.+0.j  0.+0.j  1.+0.j]


In [12]:
print(np.array([-1,0,1], dtype = np.bool_))

[ True False  True]


In [14]:
print(np.array([[1,2],[3,4]]))

[[1 2]
 [3 4]]


In [15]:
print(np.array([[[1,2],[3,4]], [[5,6],[7,8]]]))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
print(np.array([[1,2],[3]]))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [17]:
a1 = np.array([0,1,2,3,4,5])

In [18]:
a2 = a1.reshape(2,3)

In [19]:
a2

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
a1[1] = 6
print(a1)

[0 6 2 3 4 5]


In [21]:
print(a2)

[[0 6 2]
 [3 4 5]]


In [22]:
a = np.array([0,1,2,3,4,5]).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [23]:
print(a.ravel())

[0 1 2 3 4 5]


In [25]:
elems = np.array([0,1,2,3,4,5])
a = elems.reshape(2,3).ravel()
elems[1] = 6
print(a)

[0 6 2 3 4 5]


In [35]:
a.dtype

dtype('int64')

In [28]:
a.shape

(6,)

In [29]:
a.ndim

1

In [30]:
a.size

6

In [31]:
a.flat

In [32]:
print(np.arange(3))

[0 1 2]


In [33]:
print(np.arange(0,1,.2))

[0.  0.2 0.4 0.6 0.8]


In [34]:
print(np.linspace(0,1,4))

[0.         0.33333333 0.66666667 1.        ]


In [36]:
print(np.zeros(4))

[0. 0. 0. 0.]


In [38]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
print(np.ones(4))

[1. 1. 1. 1.]


In [40]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [41]:
print(np.random.rand(4))

[0.97303821 0.63631897 0.48427249 0.16749364]


In [44]:
print(np.random.rand(2,3))

[[0.13440568 0.08150704 0.58525894]
 [0.90820252 0.92847203 0.84733871]]


In [9]:
def arange_square_matrix(n):
    return np.array([np.arange(i, n+i) for i in range(n)])
arange_square_matrix(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [10]:
a = np.arange(3)
print(a)

[0 1 2]


In [11]:
a[0]

0

In [12]:
a[-1]

2

In [13]:
a[-1] = 3
print(a)

[0 1 3]


In [14]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [15]:
print(a[1:4])

[1 2 3]


In [16]:
print(a[1:])

[1 2 3 4]


In [18]:
print(a[:-2])

[0 1 2]


In [19]:
print(a[::2])

[0 2 4]


In [20]:
print(a[::-1])

[4 3 2 1 0]


In [21]:
a = np.arange(5)
a[1:4] = 6
print(a)

[0 6 6 6 4]


In [22]:
a = np.arange(5)
a[::2] = 6
print(a)

[6 1 6 3 6]


In [23]:
a = [0,1,2,3,4]
a[1:4] = 6

TypeError: can only assign an iterable

In [24]:
a = [0,1,2,3,4]
a[1:4] = [6]
print(a)

[0, 6, 4]


In [25]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
print(a[:2,:2])

[[0 1]
 [3 4]]


In [27]:
print(a[1:,1:])

[[4 5]
 [7 8]]


In [28]:
for v in np.arange(3):
    print(v)

0
1
2


In [29]:
for row in np.arange(6).reshape(2,3):
    print(row)

[0 1 2]
[3 4 5]


In [30]:
for idx, e in np.ndenumerate(np.arange(6).reshape(2,3)):
    print(idx, e)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5


In [31]:
for idx, e in np.ndenumerate(np.arange(3)):
    print(idx, e)

(0,) 0
(1,) 1
(2,) 2


In [34]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [35]:
print(a+1)

[1 2 3 4 5]


In [36]:
print(a-1)

[-1  0  1  2  3]


In [37]:
print(a*2)

[0 2 4 6 8]


In [38]:
print(a/2)

[0.  0.5 1.  1.5 2. ]


In [39]:
print(a//2)

[0 0 1 1 2]


In [40]:
print(a%2)

[0 1 0 1 0]


In [41]:
print(a**2)

[ 0  1  4  9 16]


In [42]:
print(1+a)

[1 2 3 4 5]


In [43]:
print(1-a)

[ 1  0 -1 -2 -3]


In [44]:
print(2*a)

[0 2 4 6 8]


In [45]:
b = a+1
print(1 / b)

[1.         0.5        0.33333333 0.25       0.2       ]


In [46]:
print(a//b)

[0 0 0 0 0]


In [47]:
print(1//b)

[1 0 0 0 0]


In [48]:
print(9//b)

[9 4 3 2 1]


In [49]:
a = np.arange(4).reshape(2,2)
b = np.arange(1,5).reshape(2,2)
print(a)

[[0 1]
 [2 3]]


In [50]:
print(b)

[[1 2]
 [3 4]]


In [51]:
print(a+b)

[[1 3]
 [5 7]]


In [52]:
print(a-b)

[[-1 -1]
 [-1 -1]]


In [53]:
print(a*b)

[[ 0  2]
 [ 6 12]]


In [54]:
print(a/b)

[[0.         0.5       ]
 [0.66666667 0.75      ]]


In [55]:
c = 3*a
print(c // b)

[[0 1]
 [2 2]]


In [56]:
print(a%b)

[[0 1]
 [2 3]]


In [57]:
print(a**b)

[[ 0  1]
 [ 8 81]]


In [58]:
a = np.zeros(3) + 2
print(a)

[2. 2. 2.]


In [59]:
print(np.sqrt(a))

[1.41421356 1.41421356 1.41421356]


In [60]:
b = np.zeros((2,2)) + 2
print(np.sqrt(b))

[[1.41421356 1.41421356]
 [1.41421356 1.41421356]]


In [61]:
print(np.sqrt(2))

1.4142135623730951


In [62]:
a = np.arange(4)
b = np.arange(1,5)
print(np.dot(a,b))

20


In [63]:
a = np.arange(4).reshape(2,2)
b = np.arange(1,5).reshape(2,2)
np.dot(a,b)

array([[ 3,  4],
       [11, 16]])

In [64]:
a = np.array([3,4,-1,0,2])
print(a)

[ 3  4 -1  0  2]


In [65]:
print(np.sort(a))

[-1  0  2  3  4]


In [66]:
a.sort()

In [67]:
print(a)

[-1  0  2  3  4]


In [68]:
a = np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [69]:
print(a.sum())

15


In [70]:
print(a.sum(0))

[3 5 7]


In [71]:
print(a.sum(1))

[ 3 12]


In [72]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [73]:
print(a < 3)

[ True  True  True False False False]


In [74]:
a = np.array([0,1,2,-3,-4,5,-6,-7])
print(a)

[ 0  1  2 -3 -4  5 -6 -7]


In [75]:
print(a[a<0])

[-3 -4 -6 -7]


In [76]:
print(a[(a<0) & (a%2 == 0)])

[-4 -6]


In [77]:
a[a<0] = 8
print(a)

[0 1 2 8 8 5 8 8]


In [78]:
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [79]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
